const icons={layers:'<path d="m8 2 6 3-6 3-6-3 6-3Z"/><path d="m2 8 6 3 6-3M2 11l6 3 6-3"/>',inbox:'<path d="M2 3h12v10H2zM2 9h3l1 2h4l1-2h3"/>',book:'<path d="M3 2h10v12H3zM5 2v12M7 5h4M7 8h4"/>',grid:'<rect x="2" y="2" width="4" height="4" rx="1"/><rect x="10" y="2" width="4" height="4" rx="1"/><rect x="2" y="10" width="4" height="4" rx="1"/><rect x="10" y="10" width="4" height="4" rx="1"/>',sliders:'<path d="M2 4h12M2 12h12"/><rect x="5" y="2" width="3" height="4" rx="1"/><rect x="9" y="10" width="3" height="4" rx="1"/>',search:'<circle cx="7" cy="7" r="4.5"/><path d="m10.5 10.5 3.5 3.5"/>',panel:'<rect x="2" y="2" width="12" height="12" rx="2"/><path d="M10 2v12"/>',arrow:'<path d="M3 8h10M9 4l4 4-4 4"/>',back:'<path d="M13 8H3m4-4L3 8l4 4"/>',close:'<path d="m4 4 8 8M12 4l-8 8"/>',alert:'<path d="M8 2 1 14h14L8 2ZM8 6v4M8 12v.1"/>',check:'<path d="m3 8 3 3 7-7"/>',file:'<path d="M4 2h5l3 3v9H4zM9 2v4h3M6 9h4M6 11h4"/>'};
const icon=n=>`<svg viewBox="0 0 16 16" aria-hidden="true">${icons[n]||icons.file}</svg>`;
function drawIcons(root=document){root.querySelectorAll('[data-icon]').forEach(el=>el.innerHTML=icon(el.dataset.icon))}drawIcons();
const fixtures=[
{id:'design',title:'A calmer Operator cockpit',feature:'Cockpit',stage:'Design',status:'review',owner:'Design agent',initials:'DA',time:'2 min ago',summary:'Bring project context, task progress and the next decision into one quiet workspace.',outcome:'A consistent cockpit that lets you inspect a task without losing sight of the project.',notes:'The proposal combines a persistent task queue, a comfortable reading area and a compact details panel. Neutral surfaces keep the work in focus; status and actions provide the emphasis.',checks:['Layout and spacing tokens documented','Task, detail and inspector patterns defined','Loading, empty and stale states specified'],next:'Review the layout and component rules before applying them to the live cockpit.'},
{id:'sync',title:'Preserve context after refresh',feature:'Cockpit',stage:'Implementation',status:'active',owner:'UI agent',initials:'UI',time:'8 min ago',summary:'Keep the selected task and reading position stable when new records arrive.',outcome:'Updates appear without moving the task you are inspecting.',notes:'This sample work item tracks restoring selection and scroll after refresh. The implementation needs source revision checks, an unavailable state for removed tasks, and recovery after a failed read.',checks:['Selected task keyed by stable ID','Existing content retained during refresh'],next:'Verify focus preservation and recovery in the actual host.'},
{id:'host',title:'Confirm the host return behavior',feature:'Host integration',stage:'Discovery',status:'blocked',owner:'Operator',initials:'OP',time:'21 min ago',summary:'Resolve the host behavior needed to return from a conversation to the cockpit.',outcome:'A dependable path from task inspection to conversation and back.',notes:'The sample record is blocked pending a host capability check. A visible window alone does not prove that the cockpit remains alive or continues receiving updates.',checks:['Test sequence documented','Host boundary recorded'],next:'Run the capability check and record whether selection can be restored.'},
{id:'history',title:'Define worker attempt records',feature:'Activity',stage:'Specification',status:'done',owner:'Core agent',initials:'CA',time:'1 hour ago',summary:'Give every attempt a clear source, recorded state and artifact reference.',outcome:'Agent activity can be understood from reliable records.',notes:'This sample specification separates task outcome from process activity. Unknown activity stays unknown, and completion points to an explicit result.',checks:['Attempt ID and source recorded','Completion evidence required','Missing heartbeat treated as unknown'],next:'Use the contract when connecting the activity adapter.'}
];
let tasks=structuredClone(fixtures),selected='design',attention=false,stale=false;const $=s=>document.querySelector(s);const labels={review:'Ready for review',active:'In progress',blocked:'Blocked',done:'Completed'};const badge=s=>`<span class="op-badge ${s}">${labels[s]}</span>`;
function setView(view){$('#cockpit-view').hidden=view!=='cockpit';$('#foundations-view').hidden=view!=='foundations';$('#cockpit-tab').setAttribute('aria-pressed',String(view==='cockpit'));$('#foundations-tab').setAttribute('aria-pressed',String(view==='foundations'));}
function renderList(){let filter=$('#filter').value,search=$('#search').value.toLowerCase();const visible=tasks.filter(t=>(!attention||['review','blocked'].includes(t.status))&&(filter==='all'||t.status===filter)&&(t.title+' '+t.feature).toLowerCase().includes(search));$('#task-list').innerHTML=visible.length?visible.map(t=>`<button class="op-task" data-task="${t.id}" aria-pressed="${t.id===selected}"><span class="op-task-top"><span class="op-avatar">${t.initials}</span><span class="op-caption op-muted">${t.feature}</span></span><span class="op-task-name">${t.title}</span><span class="op-task-meta">${badge(t.status)}<span>${t.time}</span></span></button>`).join(''):'<div class="op-empty">No tasks match.<br><small>Try a different status or search.</small></div>';$('#queue-foot').textContent=`${visible.length} tasks · Sample workspace`;$('#attention-nav .op-count').textContent=tasks.filter(t=>['review','blocked'].includes(t.status)).length;$('#task-list').querySelectorAll('[data-task]').forEach(b=>b.onclick=()=>{selected=b.dataset.task;$('#shell').classList.add('mobile-detail');render();$('#detail-content').scrollTop=0;(innerWidth<640?$('#detail-content h1'):$('#task-list').querySelector(`[data-task="${selected}"]`))?.focus({preventScroll:true})});}
function renderDetail(){const t=tasks.find(t=>t.id===selected);$('#detail-crumb').textContent=t.feature+' / '+t.stage;$('#detail-content').innerHTML=`<section>${badge(t.status)}<h1 tabindex="-1">${t.title}</h1><p class="op-reading op-muted">${t.summary}</p><div class="op-document"><h3>Intended outcome</h3><p class="op-reading">${t.outcome}</p><p class="op-reading op-muted">${t.notes}</p><ul>${t.checks.map(c=>`<li>${icon('check')}<span>${c}</span></li>`).join('')}</ul><div class="op-caption op-muted">${t.next}</div></div></section><section><h2>Artifacts</h2><a class="op-artifact" href="README.md" target="_blank">${icon('file')}<span><strong>Design system guide</strong><small>Foundations, provenance and adoption plan</small></span>${icon('arrow')}</a><a class="op-artifact" href="components.md" target="_blank">${icon('grid')}<span><strong>Component specifications</strong><small>Layout, behavior and interaction states</small></span>${icon('arrow')}</a></section><section><h2>Recent activity</h2><ol class="op-timeline"><li><strong>${t.owner} updated the sample record</strong>${t.time} · ${labels[t.status]}</li><li><strong>Outcome and acceptance criteria added</strong>Earlier today · Operator</li></ol></section>`;$('#inspector-content').innerHTML=`<section><h3>Information</h3><dl class="op-props"><dt>Status</dt><dd>${badge(t.status)}</dd><dt>Assigned</dt><dd><span class="op-person"><span class="op-avatar">${t.initials}</span>${t.owner}</span></dd><dt>Feature</dt><dd>${t.feature}</dd><dt>Stage</dt><dd>${t.stage}</dd><dt>Updated</dt><dd>${t.time}</dd></dl></section><section><h3>Context</h3><dl class="op-props"><dt>Project</dt><dd>Agent Operator Kit</dd><dt>Task</dt><dd class="op-mono">sample-${t.id}</dd><dt>Source</dt><dd>Design fixture</dd><dt>Activity</dt><dd>Not connected</dd></dl></section><section><h3>Next step</h3><p class="op-caption">${t.next}</p></section>`;$('#stale-banner').hidden=!stale;$('#sync-label').textContent=stale?'Sample connection paused':'Sample snapshot · Updated '+t.time;}
function render(){renderList();renderDetail()}
$('#filter').onchange=renderList;$('#search').oninput=renderList;
function queueMode(value){attention=value;$('#queue-title').textContent=value?'Needs attention':'All work';$('#all-nav').removeAttribute('aria-current');$('#attention-nav').removeAttribute('aria-current');$(value?'#attention-nav':'#all-nav').setAttribute('aria-current','page');$('#filter').value='all';renderList()}
$('#all-nav').onclick=()=>queueMode(false);$('#attention-nav').onclick=()=>queueMode(true);
function toggleInspector(close=false){const shell=$('#shell');if(innerWidth<1200){shell.classList.toggle('show-inspector',close?false:!shell.classList.contains('show-inspector'));$('#toggle-details').setAttribute('aria-expanded',String(shell.classList.contains('show-inspector')))}else{shell.classList.toggle('no-inspector',close?true:!shell.classList.contains('no-inspector'));$('#toggle-details').setAttribute('aria-expanded',String(!shell.classList.contains('no-inspector')))}}
$('#toggle-details').onclick=()=>toggleInspector();$('#close-details').onclick=()=>{toggleInspector(true);$('#toggle-details').focus()};$('#back').onclick=()=>{$('#shell').classList.remove('mobile-detail');$('#task-list').querySelector(`[data-task="${selected}"]`)?.focus()};
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&$('#shell').classList.contains('show-inspector')){$('#shell').classList.remove('show-inspector');$('#toggle-details').setAttribute('aria-expanded','false');$('#toggle-details').focus()}});
function handoff(){let t=tasks.find(t=>t.id===selected);$('#dialog-title').textContent=t.title;$('#dialog-copy').textContent=t.outcome+' '+t.next;$('#handoff-dialog').showModal()}$('#handoff').onclick=handoff;$('#example-primary').onclick=handoff;$('#example-secondary').onclick=()=>{setView('cockpit');if(innerWidth<1200)$('#shell').classList.add('show-inspector');else $('#shell').classList.remove('no-inspector')};
$('#cockpit-tab').onclick=()=>setView('cockpit');$('#foundations-tab').onclick=()=>setView('foundations');$('#tokens-nav').onclick=()=>setView('foundations');
let toastTimer;function toast(text){$('#toast').textContent=text;$('#toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').hidden=true,3500)}
$('#simulate-stale').onclick=()=>{stale=true;renderDetail();setView('cockpit');$('#shell').classList.add('mobile-detail')};$('#retry').onclick=()=>{stale=false;renderDetail();toast('Sample connection restored. Selection preserved.')};
$('#simulate-complete').onclick=()=>{tasks.find(t=>t.id==='sync').status='done';tasks.find(t=>t.id==='sync').time='Just now';const scroll=$('#detail-content').scrollTop;render();$('#detail-content').scrollTop=scroll;setView('cockpit');toast('Sample worker task completed. Your selection stayed in place.')};
$('#reset-demo').onclick=()=>{tasks=structuredClone(fixtures);selected='design';stale=false;attention=false;$('#filter').value='all';$('#search').value='';queueMode(false);render();toast('Sample workspace reset.')};
const swatches=[['Canvas','#FFFFFF'],['Sidebar','#FAFAFA'],['Surface','#FFFFFF'],['Selected','#F0F0F2'],['Primary ink','#202124'],['Secondary ink','#62646C'],['Success','#276548'],['Needs attention','#845310'],['Review','#4658A4'],['Focus','#455EC7']];$('#palette').innerHTML=swatches.map(([n,c])=>`<div class="swatch-item"><div class="swatch" style="background:${c}"></div>${n}<br><code>${c}</code></div>`).join('');$('#spacing').innerHTML=[4,8,12,16,20,24,32,40,48].map(n=>`<div class="space-row"><code>${n} px</code><span class="space-block" style="width:${n*3}px"></span></div>`).join('');render();if(innerWidth<1200)$('#toggle-details').setAttribute('aria-expanded','false');

function syncInspectorState(){const shell=$('#shell');$('#toggle-details').setAttribute('aria-expanded',String(innerWidth<1200?shell.classList.contains('show-inspector'):!shell.classList.contains('no-inspector')))}
window.addEventListener('resize',syncInspectorState);syncInspectorState();

const themeSwatches=[["Canvas","canvas"],["Sidebar","sidebar"],["Surface","surface"],["Selected","selected"],["Primary ink","text"],["Secondary ink","text-secondary"],["Success","success"],["Needs attention","warning"],["Review","info"],["Focus","focus"]];
function setTheme(theme){document.documentElement.dataset.theme=theme;const dark=theme==='dark';$('#theme-toggle').textContent=dark?'Dark theme':'Light theme';$('#theme-toggle').setAttribute('aria-pressed',String(dark));$('#theme-toggle').setAttribute('aria-label',dark?'Dark theme, switch to light':'Light theme, switch to dark');const style=getComputedStyle(document.documentElement);$('#palette').innerHTML=themeSwatches.map(([label,key])=>{const color=style.getPropertyValue('--op-color-'+key).trim();return `<div class="swatch-item"><div class="swatch" style="background:${color}"></div>${label}<br><code>${color}</code></div>`}).join('')}
$('#theme-toggle').onclick=()=>setTheme(document.documentElement.dataset.theme==='dark'?'light':'dark');setTheme('dark');

// Keep meaningful labels and hover descriptions when the sidebar becomes an icon rail.
document.querySelectorAll('.op-sidebar .op-nav-item').forEach(item=>{item.title=item.textContent.trim();for(const node of [...item.childNodes]){if(node.nodeType===Node.TEXT_NODE&&node.textContent.trim()){const label=document.createElement('span');label.className='op-nav-text';label.textContent=node.textContent;node.replaceWith(label)}}});
$('#toggle-sidebar').onclick=()=>{const collapsed=$('#shell').classList.toggle('sidebar-collapsed');const button=$('#toggle-sidebar');button.setAttribute('aria-expanded',String(!collapsed));button.setAttribute('aria-label',collapsed?'Expand sidebar':'Collapse sidebar');button.title=collapsed?'Expand sidebar':'Collapse sidebar'};
